apiVersion: v2
name: pyrra
# renovate: github=pyrra-dev/pyrra
appVersion: v0.9.2
version: 0.19.3
description: SLO manager and alert generator
sources:
  - https://github.com/pyrra-dev/pyrra
type: application
